import type { Metadata } from 'next';
import classNames from 'classnames/bind';
import '../styles/globals.scss';
import ReactQueryProvider from '../../providers/ReactQueryProvider';
import NavigationBar from '@/components/NavigationBar';
import { ModalStoreProvider } from '../../providers/ModalStoreProvider';
import ProgressBar from '@/components/Loading/Nprogress';
import styles from './layout.module.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cx = classNames.bind(styles);

  return (
    <html lang='ko'>
      <body>
        <ProgressBar />
        <ReactQueryProvider>
          <ModalStoreProvider>
            <NavigationBar />
            <div className={cx('container')}>{children}</div>
          </ModalStoreProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
