import type { Metadata } from 'next';
import '../styles/globals.scss';
import ReactQueryProvider from '../../providers/ReactQueryProvider';
import NavigationBar from '@/components/NavigationBar';
import { ModalStoreProvider } from '../../providers/ModalStoreProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <ReactQueryProvider>
          <ModalStoreProvider>
            <NavigationBar />
            {children}
          </ModalStoreProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
